all_tests:
  only: [ main, merge_requests ]
  stage: test
  needs: []
  image: jbigot/voicexx_env
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script: |
    mkdir build
    cd build
    cmake ..
    make -j 2 VERBOSE=1
    ctest --output-on-failure --timeout 5
    cd ..
    find src tests '(' -name '*.h' -o -name '*.cpp' ')' -exec clang-format -n -Werror '{}' '+' && echo "Identation is Ok!"
