name: "Build code"

inputs:
  toolchain:
    description: "The toolchain that describes the parameters for cmake"
    required: true

runs:
  using: "composite"
  steps:
    - name: Compile code
      run: |
        cmake -DCMAKE_TOOLCHAIN=toolchains/docker.gyselalibxx_env/${{ inputs.toolchain }}.cmake -B build -S .
        cmake --build build
      shell: bash

