Mesh:
  x_min: 0.0
  x_max: 12.56637061435917
  x_size: 128
  vx_min: -6.0
  vx_max: +6.0
  vx_size: 127

Equilibrium:
  ion_charge: 1
  ion_mass: 2.
  ion_density_eq: 1.
  ion_temperature_eq: 1.
  ion_mean_velocity_eq: 0.
  electron_charge: -1
  electron_mass: 0.0005
  electron_density_eq: 1.
  electron_temperature_eq: 1.
  electron_mean_velocity_eq: 0.

Perturbation:
  mode: 1
  amplitude: 0.01

Algorithm:
  deltat: 0.125
  nbiter: 360

Output:
  time_diag: 0.5
