Mesh:
  x_min: 0.0
  x_max: 12.56637061435917
  x_size: 128
  vx_min: -6.0
  vx_max: +6.0
  vx_size: 127

SpeciesInfo:
  charge: [-1, 1]
  mass: [0.0005, 2.]
  density_eq: [1., 1.]
  temperature_eq: [1., 1.]
  mean_velocity_eq: [0., 0.]

Perturbation:
  mode: [1, 1]
  amplitude: [0.01, 0.01]

Algorithm:
  deltat: 0.125
  nbiter: 360

Output:
  time_diag: 0.25
