name: Flag checks

# This PR is triggered when the "Ready to review" label is added on a draft PR.
# It leaves a comment to remind that the "Ready to review" label is not supposed
# to be used on draft PRs. It then removes the erroneous label.

on:
  pull_request:
    types:
      - labeled

jobs:
  Check_flags:
    name: Check flags
    runs-on: ubuntu-latest
    #if: github.event.label.name == 'Ready to review' && github.event.pull_request.draft
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - run: |
          echo "The added label is '${{ github.event.label.name }}'"
          echo "The draft status is '${{ github.event.pull_request.draft }}'"
      - run: |
          gh pr edit ${{ github.event.pull_request.number }} --remove-label "Ready to review"
          msg="Please remove the draft status if the PR is ready to review. The 'Ready to review' label will be added automatically when the tests are shown to be passing"
          gh pr comment ${{ github.event.pull_request.number }} -b ${msg}
        shell: bash
        if: github.event.label.name == 'Ready to review' && github.event.pull_request.draft
        env:
          GH_TOKEN: ${{ github.token }}

