name: Acceptance tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  merge_group:
    types:
      - checks_requested

jobs:
  cpu_tests:
    strategy:
      matrix:
        toolchain: [tests_toolchain, tests_release_toolchain, tests_release_omp_toolchain]
    name: CPU Test (${{ matrix.toolchain }})
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/cpu_tests.yml
    with:
      toolchain: ${{ matrix.toolchain }}
      merge_target: ${{ github.event.pull_request.base.ref }}
      pr_number: ${{ github.event.pull_request.number }}

  gpu_tests:
    name: GPU Test (${{ matrix.toolchain }})
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/gpu_tests.yml
    with:
      toolchain: ./toolchains/v100.persee/toolchain.cmake
      merge_target: ${{ github.event.pull_request.base.ref }}
      pr_number: ${{ github.event.pull_request.number }}
